<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CoursesTableSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('courses')->insert([
            [
                'id' => 12,
                'category_id' => 7,
                'name' => 'જ્ઞાનસાધન english  medium',
                'slug' => 'english-medium',
                'description' => null,
                'icon_url' => 'fa-solid fa-chart-simple',
                'color_code' => '#7B1FA2',
                'thumbnail_url' => null,
                'price' => '0.00',
                'is_free' => '0',
                'is_recommended' => '0',
                'status' => 'active',
                'sort_order' => 4,
                'created_at' => '2026-03-18 15:24:25',
                'updated_at' => '2026-03-21 16:53:31',
                'deleted_at' => '2026-03-21 16:53:31',
            ],
            [
                'id' => 25,
                'category_id' => 7,
                'name' => 'ધોરણ 4',
                'slug' => 'std-4',
                'description' => 'ધોરણ 4 complete curriculum',
                'icon_url' => 'fa-solid fa-graduation-cap',
                'color_code' => '#1565C0',
                'thumbnail_url' => null,
                'price' => '999.00',
                'is_free' => '0',
                'is_recommended' => '0',
                'status' => 'active',
                'sort_order' => 1,
                'created_at' => '2026-03-21 10:21:53',
                'updated_at' => '2026-03-21 10:21:53',
                'deleted_at' => null,
            ],
            [
                'id' => 26,
                'category_id' => 7,
                'name' => 'ધોરણ 5',
                'slug' => 'std-5',
                'description' => 'ધોરણ 5 complete curriculum',
                'icon_url' => 'fa-solid fa-graduation-cap',
                'color_code' => '#1565C0',
                'thumbnail_url' => null,
                'price' => '999.00',
                'is_free' => '0',
                'is_recommended' => '0',
                'status' => 'active',
                'sort_order' => 2,
                'created_at' => '2026-03-21 10:21:53',
                'updated_at' => '2026-03-21 10:21:53',
                'deleted_at' => null,
            ],
            [
                'id' => 27,
                'category_id' => 7,
                'name' => 'ધોરણ 6',
                'slug' => 'std-6',
                'description' => 'ધોરણ 6 complete curriculum',
                'icon_url' => 'fa-solid fa-graduation-cap',
                'color_code' => '#1565C0',
                'thumbnail_url' => null,
                'price' => '999.00',
                'is_free' => '0',
                'is_recommended' => '0',
                'status' => 'active',
                'sort_order' => 3,
                'created_at' => '2026-03-21 10:21:53',
                'updated_at' => '2026-03-21 10:21:53',
                'deleted_at' => null,
            ],
            [
                'id' => 28,
                'category_id' => 7,
                'name' => 'ધોરણ 7',
                'slug' => 'std-7',
                'description' => 'ધોરણ 7 complete curriculum',
                'icon_url' => 'fa-solid fa-graduation-cap',
                'color_code' => '#1565C0',
                'thumbnail_url' => null,
                'price' => '999.00',
                'is_free' => '0',
                'is_recommended' => '0',
                'status' => 'active',
                'sort_order' => 4,
                'created_at' => '2026-03-21 10:21:53',
                'updated_at' => '2026-03-21 10:21:53',
                'deleted_at' => null,
            ],
            [
                'id' => 29,
                'category_id' => 7,
                'name' => 'ધોરણ 8',
                'slug' => 'std-8',
                'description' => 'ધોરણ 8 complete curriculum',
                'icon_url' => 'fa-solid fa-graduation-cap',
                'color_code' => '#1565C0',
                'thumbnail_url' => null,
                'price' => '999.00',
                'is_free' => '0',
                'is_recommended' => '0',
                'status' => 'active',
                'sort_order' => 5,
                'created_at' => '2026-03-21 10:21:53',
                'updated_at' => '2026-03-21 10:21:53',
                'deleted_at' => null,
            ],
            [
                'id' => 30,
                'category_id' => 8,
                'name' => 'ધોરણ 9',
                'slug' => 'std-9',
                'description' => 'ધોરણ 9 complete curriculum',
                'icon_url' => 'fa-solid fa-graduation-cap',
                'color_code' => '#1565C0',
                'thumbnail_url' => null,
                'price' => '999.00',
                'is_free' => '0',
                'is_recommended' => '0',
                'status' => 'active',
                'sort_order' => 1,
                'created_at' => '2026-03-21 10:21:53',
                'updated_at' => '2026-03-21 10:21:53',
                'deleted_at' => null,
            ],
            [
                'id' => 31,
                'category_id' => 8,
                'name' => 'ધોરણ 10',
                'slug' => 10,
                'description' => 'ધોરણ 10 complete curriculum',
                'icon_url' => 'fa-solid fa-graduation-cap',
                'color_code' => '#1565C0',
                'thumbnail_url' => null,
                'price' => '999.00',
                'is_free' => '0',
                'is_recommended' => 1,
                'status' => 'active',
                'sort_order' => 2,
                'created_at' => '2026-03-21 10:21:53',
                'updated_at' => '2026-03-21 10:26:23',
                'deleted_at' => null,
            ],
            [
                'id' => 32,
                'category_id' => 9,
                'name' => 'જ્ઞાનસાધના  ગુજરાતી મીડિયમ',
                'slug' => '',
                'description' => null,
                'icon_url' => 'fa-solid fa-graduation-cap',
                'color_code' => '#C2185B',
                'thumbnail_url' => null,
                'price' => '0.00',
                'is_free' => 1,
                'is_recommended' => '0',
                'status' => 'active',
                'sort_order' => 6,
                'created_at' => '2026-03-21 17:01:57',
                'updated_at' => '2026-03-21 17:01:57',
                'deleted_at' => null,
            ],
        ]);

    }
}
