<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StudentsTableSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('students')->insert([
            [
                'id' => 1,
                'name' => 'Student 1',
                'email' => 'student1@example.com',
                'mobile' => 9876543211,
                'avatar_url' => null,
                'plan' => 'free',
                'status' => 'active',
                'mobile_verified_at' => null,
                'email_verified_at' => null,
                'created_at' => '2026-03-18 12:38:54',
                'updated_at' => '2026-03-18 12:38:54',
                'course_id' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 2,
                'name' => 'Student 2',
                'email' => 'student2@example.com',
                'mobile' => 9876543212,
                'avatar_url' => null,
                'plan' => 'premium',
                'status' => 'active',
                'mobile_verified_at' => null,
                'email_verified_at' => null,
                'created_at' => '2026-03-18 12:38:54',
                'updated_at' => '2026-03-18 12:38:54',
                'course_id' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 3,
                'name' => 'Student 3',
                'email' => 'student3@example.com',
                'mobile' => 9876543213,
                'avatar_url' => null,
                'plan' => 'free',
                'status' => 'active',
                'mobile_verified_at' => null,
                'email_verified_at' => null,
                'created_at' => '2026-03-18 12:38:54',
                'updated_at' => '2026-03-18 12:38:54',
                'course_id' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 4,
                'name' => 'Student 4',
                'email' => 'student4@example.com',
                'mobile' => 9876543214,
                'avatar_url' => null,
                'plan' => 'premium',
                'status' => 'active',
                'mobile_verified_at' => null,
                'email_verified_at' => null,
                'created_at' => '2026-03-18 12:38:54',
                'updated_at' => '2026-03-18 12:38:54',
                'course_id' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 5,
                'name' => 'Student 5',
                'email' => 'student5@example.com',
                'mobile' => 9876543215,
                'avatar_url' => null,
                'plan' => 'free',
                'status' => 'active',
                'mobile_verified_at' => null,
                'email_verified_at' => null,
                'created_at' => '2026-03-18 12:38:54',
                'updated_at' => '2026-03-18 12:38:54',
                'course_id' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 6,
                'name' => 'Student 6',
                'email' => 'student6@example.com',
                'mobile' => 9876543216,
                'avatar_url' => null,
                'plan' => 'premium',
                'status' => 'active',
                'mobile_verified_at' => null,
                'email_verified_at' => null,
                'created_at' => '2026-03-18 12:38:54',
                'updated_at' => '2026-03-18 12:38:54',
                'course_id' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 7,
                'name' => 'Student 7',
                'email' => 'student7@example.com',
                'mobile' => 9876543217,
                'avatar_url' => null,
                'plan' => 'free',
                'status' => 'active',
                'mobile_verified_at' => null,
                'email_verified_at' => null,
                'created_at' => '2026-03-18 12:38:54',
                'updated_at' => '2026-03-18 12:38:54',
                'course_id' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 8,
                'name' => 'Student 8',
                'email' => 'student8@example.com',
                'mobile' => 9876543218,
                'avatar_url' => null,
                'plan' => 'premium',
                'status' => 'active',
                'mobile_verified_at' => null,
                'email_verified_at' => null,
                'created_at' => '2026-03-18 12:38:54',
                'updated_at' => '2026-03-18 12:38:54',
                'course_id' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 9,
                'name' => 'Student 9',
                'email' => 'student9@example.com',
                'mobile' => 9876543219,
                'avatar_url' => null,
                'plan' => 'free',
                'status' => 'active',
                'mobile_verified_at' => null,
                'email_verified_at' => null,
                'created_at' => '2026-03-18 12:38:54',
                'updated_at' => '2026-03-18 12:38:54',
                'course_id' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 10,
                'name' => 'Student 10',
                'email' => 'student10@example.com',
                'mobile' => 98765432110,
                'avatar_url' => null,
                'plan' => 'premium',
                'status' => 'active',
                'mobile_verified_at' => null,
                'email_verified_at' => null,
                'created_at' => '2026-03-18 12:38:54',
                'updated_at' => '2026-03-18 12:38:54',
                'course_id' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 11,
                'name' => 'kalp',
                'email' => 'kalp.5871@gmail.com',
                'mobile' => null,
                'avatar_url' => null,
                'plan' => 'free',
                'status' => 'active',
                'mobile_verified_at' => null,
                'email_verified_at' => '2026-03-18 12:39:41',
                'created_at' => '2026-03-18 12:39:41',
                'updated_at' => '2026-03-18 12:39:41',
                'course_id' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 12,
                'name' => 'JITEN Solanki',
                'email' => 'jitensolanki664@gmail.com',
                'mobile' => null,
                'avatar_url' => null,
                'plan' => 'free',
                'status' => 'active',
                'mobile_verified_at' => null,
                'email_verified_at' => '2026-03-18 16:27:31',
                'created_at' => '2026-03-18 16:27:31',
                'updated_at' => '2026-03-18 16:27:31',
                'course_id' => null,
                'deleted_at' => null,
            ],
        ]);

    }
}
