<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SubjectsTableSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('subjects')->insert([
            [
                'id' => 37,
                'course_id' => 25,
                'name' => 'ગણિત',
                'slug' => 'std-4-maths',
                'description' => 'ગણિત curriculum for ધોરણ 4',
                'icon_url' => 'fa-solid fa-calculator',
                'color_code' => '#1565C0',
                'thumbnail_url' => null,
                'price' => '499.00',
                'is_free' => '0',
                'status' => 'active',
                'sort_order' => 1,
                'created_at' => '2026-03-21 10:21:53',
                'updated_at' => '2026-03-21 10:21:53',
                'deleted_at' => null,
            ],
            [
                'id' => 38,
                'course_id' => 25,
                'name' => 'આપણી આસપાસ',
                'slug' => '',
                'description' => 'વિજ્ઞાન curriculum for ધોરણ 4',
                'icon_url' => 'fa-solid fa-microscope',
                'color_code' => '#1565C0',
                'thumbnail_url' => null,
                'price' => '499.00',
                'is_free' => '0',
                'status' => 'active',
                'sort_order' => 2,
                'created_at' => '2026-03-21 10:21:53',
                'updated_at' => '2026-03-21 16:54:18',
                'deleted_at' => null,
            ],
            [
                'id' => 39,
                'course_id' => 25,
                'name' => 'સામાજિક વિજ્ઞાન',
                'slug' => 'std-4-social-science',
                'description' => 'સામાજિક વિજ્ઞાન curriculum for ધોરણ 4',
                'icon_url' => 'fa-solid fa-earth-americas',
                'color_code' => '#1565C0',
                'thumbnail_url' => null,
                'price' => '499.00',
                'is_free' => '0',
                'status' => 'active',
                'sort_order' => 3,
                'created_at' => '2026-03-21 10:21:53',
                'updated_at' => '2026-03-21 10:21:53',
                'deleted_at' => null,
            ],
            [
                'id' => 40,
                'course_id' => 25,
                'name' => 'English',
                'slug' => 'std-4-english',
                'description' => 'English curriculum for ધોરણ 4',
                'icon_url' => 'fa-solid fa-language',
                'color_code' => '#1565C0',
                'thumbnail_url' => null,
                'price' => '499.00',
                'is_free' => '0',
                'status' => 'active',
                'sort_order' => 4,
                'created_at' => '2026-03-21 10:21:53',
                'updated_at' => '2026-03-21 10:21:53',
                'deleted_at' => null,
            ],
            [
                'id' => 41,
                'course_id' => 26,
                'name' => 'ગણિત',
                'slug' => 'std-5-maths',
                'description' => 'ગણિત curriculum for ધોરણ 5',
                'icon_url' => 'fa-solid fa-calculator',
                'color_code' => '#1565C0',
                'thumbnail_url' => null,
                'price' => '499.00',
                'is_free' => '0',
                'status' => 'active',
                'sort_order' => 1,
                'created_at' => '2026-03-21 10:21:53',
                'updated_at' => '2026-03-21 10:21:53',
                'deleted_at' => null,
            ],
            [
                'id' => 42,
                'course_id' => 26,
                'name' => 'વિજ્ઞાન',
                'slug' => 'std-5-science',
                'description' => 'વિજ્ઞાન curriculum for ધોરણ 5',
                'icon_url' => 'fa-solid fa-microscope',
                'color_code' => '#1565C0',
                'thumbnail_url' => null,
                'price' => '499.00',
                'is_free' => '0',
                'status' => 'active',
                'sort_order' => 2,
                'created_at' => '2026-03-21 10:21:53',
                'updated_at' => '2026-03-21 10:21:53',
                'deleted_at' => null,
            ],
            [
                'id' => 43,
                'course_id' => 26,
                'name' => 'સામાજિક વિજ્ઞાન',
                'slug' => 'std-5-social-science',
                'description' => 'સામાજિક વિજ્ઞાન curriculum for ધોરણ 5',
                'icon_url' => 'fa-solid fa-earth-americas',
                'color_code' => '#1565C0',
                'thumbnail_url' => null,
                'price' => '499.00',
                'is_free' => '0',
                'status' => 'active',
                'sort_order' => 3,
                'created_at' => '2026-03-21 10:21:53',
                'updated_at' => '2026-03-21 10:21:53',
                'deleted_at' => null,
            ],
            [
                'id' => 44,
                'course_id' => 26,
                'name' => 'English',
                'slug' => 'std-5-english',
                'description' => 'English curriculum for ધોરણ 5',
                'icon_url' => 'fa-solid fa-language',
                'color_code' => '#1565C0',
                'thumbnail_url' => null,
                'price' => '499.00',
                'is_free' => '0',
                'status' => 'active',
                'sort_order' => 4,
                'created_at' => '2026-03-21 10:21:53',
                'updated_at' => '2026-03-21 10:21:53',
                'deleted_at' => null,
            ],
            [
                'id' => 45,
                'course_id' => 27,
                'name' => 'ગણિત',
                'slug' => 'std-6-maths',
                'description' => 'ગણિત curriculum for ધોરણ 6',
                'icon_url' => 'fa-solid fa-calculator',
                'color_code' => '#1565C0',
                'thumbnail_url' => null,
                'price' => '499.00',
                'is_free' => '0',
                'status' => 'active',
                'sort_order' => 1,
                'created_at' => '2026-03-21 10:21:53',
                'updated_at' => '2026-03-21 10:21:53',
                'deleted_at' => null,
            ],
            [
                'id' => 46,
                'course_id' => 27,
                'name' => 'વિજ્ઞાન',
                'slug' => 'std-6-science',
                'description' => 'વિજ્ઞાન curriculum for ધોરણ 6',
                'icon_url' => 'fa-solid fa-microscope',
                'color_code' => '#1565C0',
                'thumbnail_url' => null,
                'price' => '499.00',
                'is_free' => '0',
                'status' => 'active',
                'sort_order' => 2,
                'created_at' => '2026-03-21 10:21:53',
                'updated_at' => '2026-03-21 10:21:53',
                'deleted_at' => null,
            ],
            [
                'id' => 47,
                'course_id' => 27,
                'name' => 'સામાજિક વિજ્ઞાન',
                'slug' => 'std-6-social-science',
                'description' => 'સામાજિક વિજ્ઞાન curriculum for ધોરણ 6',
                'icon_url' => 'fa-solid fa-earth-americas',
                'color_code' => '#1565C0',
                'thumbnail_url' => null,
                'price' => '499.00',
                'is_free' => '0',
                'status' => 'active',
                'sort_order' => 3,
                'created_at' => '2026-03-21 10:21:53',
                'updated_at' => '2026-03-21 10:21:53',
                'deleted_at' => null,
            ],
            [
                'id' => 48,
                'course_id' => 27,
                'name' => 'English',
                'slug' => 'std-6-english',
                'description' => 'English curriculum for ધોરણ 6',
                'icon_url' => 'fa-solid fa-language',
                'color_code' => '#1565C0',
                'thumbnail_url' => null,
                'price' => '499.00',
                'is_free' => '0',
                'status' => 'active',
                'sort_order' => 4,
                'created_at' => '2026-03-21 10:21:53',
                'updated_at' => '2026-03-21 10:21:53',
                'deleted_at' => null,
            ],
            [
                'id' => 49,
                'course_id' => 28,
                'name' => 'ગણિત',
                'slug' => 'std-7-maths',
                'description' => 'ગણિત curriculum for ધોરણ 7',
                'icon_url' => 'fa-solid fa-calculator',
                'color_code' => '#1565C0',
                'thumbnail_url' => null,
                'price' => '499.00',
                'is_free' => '0',
                'status' => 'active',
                'sort_order' => 1,
                'created_at' => '2026-03-21 10:21:53',
                'updated_at' => '2026-03-21 10:21:53',
                'deleted_at' => null,
            ],
            [
                'id' => 50,
                'course_id' => 28,
                'name' => 'વિજ્ઞાન',
                'slug' => 'std-7-science',
                'description' => 'વિજ્ઞાન curriculum for ધોરણ 7',
                'icon_url' => 'fa-solid fa-microscope',
                'color_code' => '#1565C0',
                'thumbnail_url' => null,
                'price' => '499.00',
                'is_free' => '0',
                'status' => 'active',
                'sort_order' => 2,
                'created_at' => '2026-03-21 10:21:53',
                'updated_at' => '2026-03-21 10:21:53',
                'deleted_at' => null,
            ],
            [
                'id' => 51,
                'course_id' => 28,
                'name' => 'સામાજિક વિજ્ઞાન',
                'slug' => 'std-7-social-science',
                'description' => 'સામાજિક વિજ્ઞાન curriculum for ધોરણ 7',
                'icon_url' => 'fa-solid fa-earth-americas',
                'color_code' => '#1565C0',
                'thumbnail_url' => null,
                'price' => '499.00',
                'is_free' => '0',
                'status' => 'active',
                'sort_order' => 3,
                'created_at' => '2026-03-21 10:21:53',
                'updated_at' => '2026-03-21 10:21:53',
                'deleted_at' => null,
            ],
            [
                'id' => 52,
                'course_id' => 28,
                'name' => 'English',
                'slug' => 'std-7-english',
                'description' => 'English curriculum for ધોરણ 7',
                'icon_url' => 'fa-solid fa-language',
                'color_code' => '#1565C0',
                'thumbnail_url' => null,
                'price' => '499.00',
                'is_free' => '0',
                'status' => 'active',
                'sort_order' => 4,
                'created_at' => '2026-03-21 10:21:53',
                'updated_at' => '2026-03-21 10:21:53',
                'deleted_at' => null,
            ],
            [
                'id' => 53,
                'course_id' => 29,
                'name' => 'ગણિત',
                'slug' => 'std-8-maths',
                'description' => 'ગણિત curriculum for ધોરણ 8',
                'icon_url' => 'fa-solid fa-calculator',
                'color_code' => '#1565C0',
                'thumbnail_url' => null,
                'price' => '499.00',
                'is_free' => '0',
                'status' => 'active',
                'sort_order' => 1,
                'created_at' => '2026-03-21 10:21:53',
                'updated_at' => '2026-03-21 10:21:53',
                'deleted_at' => null,
            ],
            [
                'id' => 54,
                'course_id' => 29,
                'name' => 'વિજ્ઞાન',
                'slug' => 'std-8-science',
                'description' => 'વિજ્ઞાન curriculum for ધોરણ 8',
                'icon_url' => 'fa-solid fa-microscope',
                'color_code' => '#1565C0',
                'thumbnail_url' => null,
                'price' => '499.00',
                'is_free' => '0',
                'status' => 'active',
                'sort_order' => 2,
                'created_at' => '2026-03-21 10:21:53',
                'updated_at' => '2026-03-21 10:21:53',
                'deleted_at' => null,
            ],
            [
                'id' => 55,
                'course_id' => 29,
                'name' => 'સામાજિક વિજ્ઞાન',
                'slug' => 'std-8-social-science',
                'description' => 'સામાજિક વિજ્ઞાન curriculum for ધોરણ 8',
                'icon_url' => 'fa-solid fa-earth-americas',
                'color_code' => '#1565C0',
                'thumbnail_url' => null,
                'price' => '499.00',
                'is_free' => '0',
                'status' => 'active',
                'sort_order' => 3,
                'created_at' => '2026-03-21 10:21:53',
                'updated_at' => '2026-03-21 10:21:53',
                'deleted_at' => null,
            ],
            [
                'id' => 56,
                'course_id' => 29,
                'name' => 'English',
                'slug' => 'std-8-english',
                'description' => 'English curriculum for ધોરણ 8',
                'icon_url' => 'fa-solid fa-language',
                'color_code' => '#1565C0',
                'thumbnail_url' => null,
                'price' => '499.00',
                'is_free' => '0',
                'status' => 'active',
                'sort_order' => 4,
                'created_at' => '2026-03-21 10:21:53',
                'updated_at' => '2026-03-21 10:21:53',
                'deleted_at' => null,
            ],
            [
                'id' => 57,
                'course_id' => 30,
                'name' => 'ગણિત',
                'slug' => 'std-9-maths',
                'description' => 'ગણિત curriculum for ધોરણ 9',
                'icon_url' => 'fa-solid fa-calculator',
                'color_code' => '#1565C0',
                'thumbnail_url' => null,
                'price' => '499.00',
                'is_free' => '0',
                'status' => 'active',
                'sort_order' => 1,
                'created_at' => '2026-03-21 10:21:53',
                'updated_at' => '2026-03-21 10:21:53',
                'deleted_at' => null,
            ],
            [
                'id' => 58,
                'course_id' => 30,
                'name' => 'વિજ્ઞાન',
                'slug' => 'std-9-science',
                'description' => 'વિજ્ઞાન curriculum for ધોરણ 9',
                'icon_url' => 'fa-solid fa-microscope',
                'color_code' => '#1565C0',
                'thumbnail_url' => null,
                'price' => '499.00',
                'is_free' => '0',
                'status' => 'active',
                'sort_order' => 2,
                'created_at' => '2026-03-21 10:21:53',
                'updated_at' => '2026-03-21 10:21:53',
                'deleted_at' => null,
            ],
            [
                'id' => 59,
                'course_id' => 30,
                'name' => 'સામાજિક વિજ્ઞાન',
                'slug' => 'std-9-social-science',
                'description' => 'સામાજિક વિજ્ઞાન curriculum for ધોરણ 9',
                'icon_url' => 'fa-solid fa-earth-americas',
                'color_code' => '#1565C0',
                'thumbnail_url' => null,
                'price' => '499.00',
                'is_free' => '0',
                'status' => 'active',
                'sort_order' => 3,
                'created_at' => '2026-03-21 10:21:53',
                'updated_at' => '2026-03-21 10:21:53',
                'deleted_at' => null,
            ],
            [
                'id' => 60,
                'course_id' => 30,
                'name' => 'English',
                'slug' => 'std-9-english',
                'description' => 'English curriculum for ધોરણ 9',
                'icon_url' => 'fa-solid fa-language',
                'color_code' => '#1565C0',
                'thumbnail_url' => null,
                'price' => '499.00',
                'is_free' => '0',
                'status' => 'active',
                'sort_order' => 4,
                'created_at' => '2026-03-21 10:21:53',
                'updated_at' => '2026-03-21 10:21:53',
                'deleted_at' => null,
            ],
            [
                'id' => 61,
                'course_id' => 31,
                'name' => 'ગણિત',
                'slug' => 'std-10-maths',
                'description' => 'ગણિત curriculum for ધોરણ 10',
                'icon_url' => 'fa-solid fa-calculator',
                'color_code' => '#1565C0',
                'thumbnail_url' => null,
                'price' => '499.00',
                'is_free' => '0',
                'status' => 'active',
                'sort_order' => 1,
                'created_at' => '2026-03-21 10:21:53',
                'updated_at' => '2026-03-21 10:21:53',
                'deleted_at' => null,
            ],
            [
                'id' => 62,
                'course_id' => 31,
                'name' => 'વિજ્ઞાન',
                'slug' => 'std-10-science',
                'description' => 'વિજ્ઞાન curriculum for ધોરણ 10',
                'icon_url' => 'fa-solid fa-microscope',
                'color_code' => '#1565C0',
                'thumbnail_url' => null,
                'price' => '499.00',
                'is_free' => '0',
                'status' => 'active',
                'sort_order' => 2,
                'created_at' => '2026-03-21 10:21:53',
                'updated_at' => '2026-03-21 10:21:53',
                'deleted_at' => null,
            ],
            [
                'id' => 63,
                'course_id' => 31,
                'name' => 'સામાજિક વિજ્ઞાન',
                'slug' => 'std-10-social-science',
                'description' => 'સામાજિક વિજ્ઞાન curriculum for ધોરણ 10',
                'icon_url' => 'fa-solid fa-earth-americas',
                'color_code' => '#1565C0',
                'thumbnail_url' => null,
                'price' => '499.00',
                'is_free' => '0',
                'status' => 'active',
                'sort_order' => 3,
                'created_at' => '2026-03-21 10:21:53',
                'updated_at' => '2026-03-21 10:21:53',
                'deleted_at' => null,
            ],
            [
                'id' => 64,
                'course_id' => 31,
                'name' => 'English',
                'slug' => 'std-10-english',
                'description' => 'English curriculum for ધોરણ 10',
                'icon_url' => 'fa-solid fa-language',
                'color_code' => '#1565C0',
                'thumbnail_url' => null,
                'price' => '499.00',
                'is_free' => '0',
                'status' => 'active',
                'sort_order' => 4,
                'created_at' => '2026-03-21 10:21:53',
                'updated_at' => '2026-03-21 10:21:53',
                'deleted_at' => null,
            ],
            [
                'id' => 68,
                'course_id' => 32,
                'name' => 'SCIENCE',
                'slug' => 'science',
                'description' => null,
                'icon_url' => 'fa-solid fa-flask',
                'color_code' => '#1565C0',
                'thumbnail_url' => null,
                'price' => '0.00',
                'is_free' => 1,
                'status' => 'active',
                'sort_order' => 1,
                'created_at' => '2026-03-21 17:02:32',
                'updated_at' => '2026-03-21 17:02:32',
                'deleted_at' => null,
            ],
            [
                'id' => 69,
                'course_id' => 32,
                'name' => 'social science',
                'slug' => 'social-science',
                'description' => null,
                'icon_url' => 'fa-solid fa-calculator',
                'color_code' => '#1565C0',
                'thumbnail_url' => null,
                'price' => '0.00',
                'is_free' => 1,
                'status' => 'active',
                'sort_order' => 2,
                'created_at' => '2026-03-21 17:03:47',
                'updated_at' => '2026-03-21 17:03:47',
                'deleted_at' => null,
            ],
            [
                'id' => 72,
                'course_id' => 30,
                'name' => 'test 9',
                'slug' => 'test-9',
                'description' => 'Description',
                'icon_url' => 'fa-solid fa-calculator',
                'color_code' => '#1565C0',
                'thumbnail_url' => null,
                'price' => '500.00',
                'is_free' => '0',
                'status' => 'active',
                'sort_order' => 5,
                'created_at' => '2026-03-23 08:36:36',
                'updated_at' => '2026-03-23 08:39:10',
                'deleted_at' => null,
            ],
            [
                'id' => 73,
                'course_id' => 25,
                'name' => 'ધોરણ 9',
                'slug' => 9,
                'description' => 'Description',
                'icon_url' => 'fa-solid fa-calculator',
                'color_code' => '#1565C0',
                'thumbnail_url' => null,
                'price' => '500.00',
                'is_free' => '0',
                'status' => 'active',
                'sort_order' => 5,
                'created_at' => '2026-03-23 08:42:28',
                'updated_at' => '2026-03-23 08:42:33',
                'deleted_at' => '2026-03-23 08:42:33',
            ],
            [
                'id' => 76,
                'course_id' => 25,
                'name' => 'ગુજરાતી',
                'slug' => 'ગજરત',
                'description' => 'Description',
                'icon_url' => 'fa-solid fa-calculator',
                'color_code' => '#1565C0',
                'thumbnail_url' => null,
                'price' => '499.00',
                'is_free' => 1,
                'status' => 'active',
                'sort_order' => 5,
                'created_at' => '2026-03-23 08:46:59',
                'updated_at' => '2026-03-23 09:14:08',
                'deleted_at' => '2026-03-23 09:14:08',
            ],
            [
                'id' => 77,
                'course_id' => 25,
                'name' => 'ગુજરાતી1',
                'slug' => 1,
                'description' => 'ગુજરાતી1',
                'icon_url' => 'fa-solid fa-calculator',
                'color_code' => '#1565C0',
                'thumbnail_url' => null,
                'price' => '500.00',
                'is_free' => 1,
                'status' => 'active',
                'sort_order' => 6,
                'created_at' => '2026-03-23 09:13:56',
                'updated_at' => '2026-03-23 09:14:02',
                'deleted_at' => '2026-03-23 09:14:02',
            ],
        ]);

    }
}
